version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - '8081:5678'
    environment:
    - DB_POSTGRESDB_DATABASE=n8n
    - DB_POSTGRESDB_HOST=db
    - DB_POSTGRESDB_PASSWORD=passwd
    - DB_POSTGRESDB_USER=postgres
    - DB_TYPE=postgresdb
    - TZ=Europe/Vienna

  db:
    image: bitnami/postgresql:latest
    environment:
    - POSTGRESQL_PASSWORD=passwd
    - POSTGRESQL_DATABASE=n8n
    - POSTGRESQL_USERNAME=postgres
    - POSTGRESQL_TIMEZONE=UTC
